# Generated by Django 5.2.3 on 2025-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('pre', 'Presencial'), ('mx', 'Mixta'), ('vr', 'Virtual')], max_length=10),
        ),
    ]
